# fly.toml file for benchmark runner
app = "host-perf-test"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"
  context = "../.."

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[http_service.checks]]
  interval = "15s"
  timeout = "5s"
  method = "GET"
  path = "/healthz"
