name = "hosting-perf-web"
main = ".output/server/index.mjs"
compatibility_date = "2025-09-01"

[vars]
# Set these in Cloudflare dashboard or here for local/dev
BENCHMARK_RUNNER_HOST = "host-perf-test.fly.dev"
GITHUB_APP_ID = ""
GITHUB_WEBHOOK_SECRET = ""
GITHUB_APP_INSTALLATION_ID = ""

# Uncomment if/when you enable D1
# [[d1_databases]]
# binding = "DB"
# database_name = "hosting-perf"
# database_id = "<your-d1-db-id>"
