name = "hosting-perf-web"
compatibility_date = "2025-09-25"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "host-perf-db"
database_id = "7f4305a3-b96f-489c-8976-4a7e8458698d"
migrations_dir = "server/database/migrations"