name: Deploy Benchmark Runner

on:
  push:
    paths:
      - 'apps/benchmark/**'
      - '.github/workflows/deploy-benchmark-runner.yml'
  workflow_dispatch:

permissions:
  contents: read

env:
  APP_NAME: host-perf-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Ensure app exists
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl apps show $APP_NAME || flyctl apps create $APP_NAME

      - name: Deploy runner
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --config apps/benchmark/fly.toml --build-arg BUILDKIT_INLINE_CACHE=1 --remote-only

